### ISSUE TITLE
Dependent Namespaces

### ISSUE THREAD

**Issue by geekcubed** [harouny/NLog.Extensions.AzureTableStorage#16]
Microsoft have released a number of updates to the Azure SDK packages, one of which is to the CloudConfiguration package.

They have changed the namespace from "Microsoft.WindowsAzure" to "Microsoft.Azure". Attempting to use this package in a project running the latest Azure SDK causes an exception, as it's trying to reference the CloudConfiguration class in the old namespace.

**Comment by harouny** [comment]
Hi @geekcubed, the change is merged and Nuget package have been updated. Thanks for your contribution.
