### ISSUE TITLE
Assembly won't load after updating Microsoft.WindowsAzure.Configuration to v3

### ISSUE THREAD

**Issue by eduardogh** [harouny/NLog.Extensions.AzureTableStorage#18]
I have the nugget package installed on a Web App project, after updating the web project packages, specially Microsoft.WindowsAzure.Configuration, log entries stop inserting.

**Comment by harouny** [comment]
Hi @eduardogh I have just pushed v 1.0.9 to Nuget. It should support working with the latest Azure SDK tools.
