### ISSUE TITLE
 Error initializing target AzureTableStorage

### ISSUE THREAD

**Issue by markhasalaptop** [harouny/NLog.Extensions.AzureTableStorage#20]
Is it still working? I can't write to table storage using this target. 
I'm debugging locally and getting this error when nlog try to log to azure table storage: 

Error Error initializing target AzureTableStorage Target[AzureTableStorageTabnet] System.ArgumentNullException: value cannot be null.
parameter name: connectionString
   in Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString)
   in NLog.Extensions.AzureTableStorage.ConfigManager.GetStorageAccount()
   in NLog.Extensions.AzureTableStorage.TableStorageManager..ctor(ConfigManager configManager, String tableName)
   in NLog.Extensions.AzureTableStorage.AzureTableStorageTarget.InitializeTarget()
   in NLog.Targets.Target.Initialize(LoggingConfiguration configuration).

I use the same connection string with Azure Storage Explorer and it is ok.

Please help me. Thanks.

**Comment by harouny** [comment]
Hi @markhasalaptop 
The ```ConnectionStringKey``` property in target configuration expects a key that is used in app settings or cloud configuration where the value is the connection string.

Example:
```
<targets>
    <target xsi:type="AzureTableStorage" 
            name="TargetName"
            ConnectionStringKey="LoggingDB" 
            TableName="Logs" />
  </targets>
```
Notice that somewhere else you need to define connection string in app settings of cloud configuration file with key ```LoggingDB``` and value is your connection string.

**Comment by markhasalaptop** [comment]
Thanks, i give u a feedback asap

2015-06-09 13:02 GMT+02:00 Ahmed EL-Harouny <notifications@github.com>:

> Hi @markhasalaptop <https://github.com/markhasalaptop>
> The ConnectionStringKey property in target configuration expects a key
> that is used in app settings or cloud configuration where the value is the
> connection string.
>
> Example:
>
> <targets>
>     <target xsi:type="AzureTableStorage"
>             name="TargetName"
>             ConnectionStringKey="LoggingDB"
>             TableName="Logs" />
>   </targets>
>
> Notice that somewhere else you need to define connection string in app
> settings of cloud configuration file with key LoggingDB and value is your
> connection string.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/harouny/NLog.Extensions.AzureTableStorage/issues/20#issuecomment-110318831>
> .
>



-- 


*Marco G.            *

**Comment by markhasalaptop** [comment]
This is my nlog.config: is it not ok simply to edit this?

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" mlns:xsi="
http://www.w3.org/2001/XMLSchema-instance">
<extensions>
    <add assembly="NLog.Extensions.AzureTableStorage"/>
  </extensions>
  <targets>
    <target xsi:type="AzureTableStorage" name="AzureTableStorage"
connectionStringKey="DefaultEndpointsProtocol=https;AccountName=********;AccountKey=*************************"
tableName="TempAzureTableStorageTargetTestsLogs" />
    <target name="Console" xsi:type="Console" layout="${longdate}
${callsite} ${level} ${message}"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="AzureTableStorage"/>
  </rules>
</nlog>


Thanks, Marco

2015-06-09 13:54 GMT+02:00 Mark <markhasalaptop@gmail.com>:

> Thanks, i give u a feedback asap
>
> 2015-06-09 13:02 GMT+02:00 Ahmed EL-Harouny <notifications@github.com>:
>
>> Hi @markhasalaptop <https://github.com/markhasalaptop>
>> The ConnectionStringKey property in target configuration expects a key
>> that is used in app settings or cloud configuration where the value is the
>> connection string.
>>
>> Example:
>>
>> <targets>
>>     <target xsi:type="AzureTableStorage"
>>             name="TargetName"
>>             ConnectionStringKey="LoggingDB"
>>             TableName="Logs" />
>>   </targets>
>>
>> Notice that somewhere else you need to define connection string in app
>> settings of cloud configuration file with key LoggingDB and value is
>> your connection string.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/harouny/NLog.Extensions.AzureTableStorage/issues/20#issuecomment-110318831>
>> .
>>
>
>
>
> --
>
>
> *Marco G.            *
>



-- 


*Marco G.            *

**Comment by markhasalaptop** [comment]
Thank you so much!

It works. The key is stored in my web.config.

Marco

2015-06-09 13:59 GMT+02:00 Mark <markhasalaptop@gmail.com>:

> This is my nlog.config: is it not ok simply to edit this?
>
> <?xml version="1.0" encoding="utf-8" ?>
> <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" mlns:xsi="
> http://www.w3.org/2001/XMLSchema-instance">
> <extensions>
>     <add assembly="NLog.Extensions.AzureTableStorage"/>
>   </extensions>
>   <targets>
>     <target xsi:type="AzureTableStorage" name="AzureTableStorage"
> connectionStringKey="DefaultEndpointsProtocol=https;AccountName=********;AccountKey=*************************"
> tableName="TempAzureTableStorageTargetTestsLogs" />
>     <target name="Console" xsi:type="Console" layout="${longdate}
> ${callsite} ${level} ${message}"/>
>   </targets>
>   <rules>
>     <logger name="*" minlevel="Trace" writeTo="AzureTableStorage"/>
>   </rules>
> </nlog>
>
>
> Thanks, Marco
>
> 2015-06-09 13:54 GMT+02:00 Mark <markhasalaptop@gmail.com>:
>
>> Thanks, i give u a feedback asap
>>
>> 2015-06-09 13:02 GMT+02:00 Ahmed EL-Harouny <notifications@github.com>:
>>
>>> Hi @markhasalaptop <https://github.com/markhasalaptop>
>>> The ConnectionStringKey property in target configuration expects a key
>>> that is used in app settings or cloud configuration where the value is the
>>> connection string.
>>>
>>> Example:
>>>
>>> <targets>
>>>     <target xsi:type="AzureTableStorage"
>>>             name="TargetName"
>>>             ConnectionStringKey="LoggingDB"
>>>             TableName="Logs" />
>>>   </targets>
>>>
>>> Notice that somewhere else you need to define connection string in app
>>> settings of cloud configuration file with key LoggingDB and value is
>>> your connection string.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/harouny/NLog.Extensions.AzureTableStorage/issues/20#issuecomment-110318831>
>>> .
>>>
>>
>>
>>
>> --
>>
>>
>> *Marco G.            *
>>
>
>
>
> --
>
>
> *Marco G.            *
>



-- 


*Marco G.            *

**Comment by markhasalaptop** [comment]
https://vmgmt.wordpress.com/2015/06/09/nlog-and-azure-table-storage/

2015-06-09 14:35 GMT+02:00 Mark <markhasalaptop@gmail.com>:

> Thank you so much!
>
> It works. The key is stored in my web.config.
>
> Marco
>
> 2015-06-09 13:59 GMT+02:00 Mark <markhasalaptop@gmail.com>:
>
>> This is my nlog.config: is it not ok simply to edit this?
>>
>> <?xml version="1.0" encoding="utf-8" ?>
>> <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" mlns:xsi="
>> http://www.w3.org/2001/XMLSchema-instance">
>> <extensions>
>>     <add assembly="NLog.Extensions.AzureTableStorage"/>
>>   </extensions>
>>   <targets>
>>     <target xsi:type="AzureTableStorage" name="AzureTableStorage"
>> connectionStringKey="DefaultEndpointsProtocol=https;AccountName=********;AccountKey=*************************"
>> tableName="TempAzureTableStorageTargetTestsLogs" />
>>     <target name="Console" xsi:type="Console" layout="${longdate}
>> ${callsite} ${level} ${message}"/>
>>   </targets>
>>   <rules>
>>     <logger name="*" minlevel="Trace" writeTo="AzureTableStorage"/>
>>   </rules>
>> </nlog>
>>
>>
>> Thanks, Marco
>>
>> 2015-06-09 13:54 GMT+02:00 Mark <markhasalaptop@gmail.com>:
>>
>>> Thanks, i give u a feedback asap
>>>
>>> 2015-06-09 13:02 GMT+02:00 Ahmed EL-Harouny <notifications@github.com>:
>>>
>>>> Hi @markhasalaptop <https://github.com/markhasalaptop>
>>>> The ConnectionStringKey property in target configuration expects a key
>>>> that is used in app settings or cloud configuration where the value is the
>>>> connection string.
>>>>
>>>> Example:
>>>>
>>>> <targets>
>>>>     <target xsi:type="AzureTableStorage"
>>>>             name="TargetName"
>>>>             ConnectionStringKey="LoggingDB"
>>>>             TableName="Logs" />
>>>>   </targets>
>>>>
>>>> Notice that somewhere else you need to define connection string in app
>>>> settings of cloud configuration file with key LoggingDB and value is
>>>> your connection string.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/harouny/NLog.Extensions.AzureTableStorage/issues/20#issuecomment-110318831>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>>
>>>
>>> *Marco G.            *
>>>
>>
>>
>>
>> --
>>
>>
>> *Marco G.            *
>>
>
>
>
> --
>
>
> *Marco G.            *
>



-- 


*Marco G.            *
