### ISSUE TITLE
Should include depenedency to Microsoft.WindowsAzure.Configuration nuget package

### ISSUE THREAD

**Issue by ryanvgates** [harouny/NLog.Extensions.AzureTableStorage#21]
I had the same issue as https://github.com/harouny/NLog.Extensions.AzureTableStorage/issues/13. I think this could be easily avoided if [Microsoft.WindowsAzure.Configuration](https://www.nuget.org/packages/Microsoft.WindowsAzure.ConfigurationManager/) were added to the list of dependencies. 

Although I don't know what the minimum version would be. Once I ran nuget for the latest, it resolved the issue.

**Comment by harouny** [comment]
Should have been fixed in v 1.0.10. Please reopen if its reproducible in v 1.0.10.
