### ISSUE TITLE
License name for this project

### ISSUE THREAD

**Issue by vaganovk** [harouny/NLog.Extensions.AzureTableStorage#25]
Could you please clarify the license under which this code is released, and whether it can be used in commercial project?

It would be great to attribute a license on a project page.

Thanks!

**Comment by harouny** [comment]
Hi vaganovk,

I have added a license in commit a309c9e0842ee644f484e644b7e2c655105f2bc8

**Comment by vaganovk** [comment]
Thanks a lot!
