### ISSUE TITLE
Microsoft.WindowsAzure.ConfigurationManager 3.2.0

### ISSUE THREAD

**Issue by ElBart00** [harouny/NLog.Extensions.AzureTableStorage#26]
Version 1.0.9 is not compatible with package Microsoft.WindowsAzure.ConfigurationManager 3.2.0
It works with Microsoft.WindowsAzure.ConfigurationManager 3.1.0

**Comment by caseyjmorris** [comment]
I ran into this same issue.  I tried cloning this repo and updating all the nuget packages and all the tests seem to pass so it might just be an issue of updating the nuget references, rebuilding, and republishing.

**Comment by harouny** [comment]
Should have been fixed in v 1.0.10. Please reopen if its reproducible in v 1.0.10.
