### ISSUE TITLE
NLog 4.2.3 causes TypeInitializationException

### ISSUE THREAD

**Issue by ryanvgates** [harouny/NLog.Extensions.AzureTableStorage#31]
I created a test project and ran the following commands in Nuget.

> Install-Package AzureTableStorageNLogTarget
> Install-Package NLog
> Install-Package NLog.Config
> Install-Package NLog.Schema

The resulting packages.config looked like below.

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AzureTableStorageNLogTarget" version="1.0.9" targetFramework="net452" />
  <package id="Microsoft.Data.Edm" version="5.6.2" targetFramework="net452" />
  <package id="Microsoft.Data.OData" version="5.6.2" targetFramework="net452" />
  <package id="Microsoft.Data.Services.Client" version="5.6.2" targetFramework="net452" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="1.8.0.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="5.0.8" targetFramework="net452" />
  <package id="NLog" version="4.2.3" targetFramework="net452" />
  <package id="NLog.Config" version="4.2.3" targetFramework="net452" />
  <package id="NLog.Schema" version="4.2.3" targetFramework="net452" />
  <package id="System.Spatial" version="5.6.2" targetFramework="net452" />
  <package id="WindowsAzure.Storage" version="4.3.0" targetFramework="net452" />
</packages>
```

Anytime I try to use the `AzureTableStorage` target in the NLog.config, I get the following exception.

> System.TypeInitializationException was unhandled
> Message: An unhandled exception of type 'System.TypeInitializationException' occurred in mscorlib.dll
> Additional information: The type initializer for 'NLogAzureTableStorageTest.Program' threw an exception.

Is there a way to make it work with the latest version of NLog?

**Comment by harouny** [comment]
Should have been fixed in v 1.0.10. Please reopen if its reproducible in v 1.0.10.
