### ISSUE TITLE
The latest NuGet package doesn't contain PartitionKeyPrefixDateFormat

### ISSUE THREAD

**Issue by seanjackson24** [harouny/NLog.Extensions.AzureTableStorage#33]
The latest version of the NuGet package (1.0.10) doesn't contain the new features from pull request #23 which added the new property PartitionKeyPrefixDateFormat. The actual version of the DLL is 1.0.4.

**Comment by harouny** [comment]
Thanks, I will check that out.

**Comment by harouny** [comment]
@seanjackson24,
Missing features are back in the recent version 1.0.11
Please check and let me know to close this up.
