### ISSUE TITLE
Parameter ConnectionStringKey not supported on AzureTableStorageTarget

### ISSUE THREAD

**Issue by WillPwn4Food** [harouny/NLog.Extensions.AzureTableStorage#35]
Same code I used in previous project that worked great and is in all the turotials now doesn't work and gives this error in the internal logs, please help!

Error Parsing configuration from xxx\web.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing xxx\web.config.  ---> System.NotSupportedException: Parameter ConnectionStringKey not supported on AzureTableStorageTarget
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---

Other relevant stuff:
target type="AzureTableStorage"
            name="azure-debug"
            ConnectionStringKey="AzureStorageConnectionString"
            TableName="Local"
			      

add key="AzureStorageConnectionString" value="DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net"

**Comment by harouny** [comment]
Thanks for reporting that. Which version you are on? Is it different from the version on projects where you don't get this error?

**Comment by WillPwn4Food** [comment]
I'm no 1.1.4 on my new project. My old project uses the same version. 
I just updated nLog after I couldn't get it to work, but it made no difference.
My old project used nLog 4.2.3 if that makes a difference.

**Comment by harouny** [comment]
Do you have this part in nlog config:

<extensions>
    <add assembly="NLog.Extensions.AzureTableStorage"/>
  </extensions>

**Comment by harouny** [comment]
'''
<extensions>
    <add assembly="NLog.Extensions.AzureTableStorage"/>
  </extensions>
'''

**Comment by harouny** [comment]
Sorry github is omitting my code. Do you have the extention    NLog.Extensions.AzureTableStorage in your extenstions
<extensions>
    <add assembly="NLog.Extensions.AzureTableStorage"/>
  </extensions>

**Comment by WillPwn4Food** [comment]
Yeah I had trouble pasting angle bracket code earlier too, here is my nlog section in the web config: https://gist.github.com/WillPwn4Food/66594502dd7b14cdb45928f4814fe6e8

It does have a section for the extension in it.

**Comment by harouny** [comment]
@WillPwn4Food 
Looks like you have installed the wrong package:
There is two packages on nuget:
https://www.nuget.org/packages/AzureTableStorageNLogTarget/ (that is the correct one, related to this repo)
https://www.nuget.org/packages/NLog.Extensions.AzureTableStorage/ (is related to a fork of that repo)
So probably what you need to do it just switch to the correct package

**Comment by WillPwn4Food** [comment]
Thanks, missed that I was on some fork!

**Comment by harouny** [comment]
No worriers, I just did the same mistake my self, didn't know that the fork exists :)
