### ISSUE TITLE
Datetime format

### ISSUE THREAD

**Issue by VaclavK** [harouny/NLog.Extensions.AzureTableStorage#8]
Hi,

it seems that it would be valuable/required to normalize format of date time - at the moment it takes format as per env format but considering the cloud/distributed nature I think there should/could be a config option to override/normalize (e..g to long format etc.)

Vaclav

**Comment by pbolduc** [comment]
Shouldn't the sink use the date type based on the nlog time source configuration?  If you want the log entries in UTC, then configure NLog to use FastUTC or AccurateUTC?

https://github.com/nlog/NLog/wiki/Time%20Source
